apiVersion: v1
kind: Namespace
metadata:
  name: fluxcd-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deployment
  template:
    metadata:
      labels:
        app: test-deployment
    spec:
      containers:
        - name: test-container
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-statefulset
spec:
  serviceName: test-statefulset
  replicas: 2
  selector:
    matchLabels:
      app: test-statefulset
  template:
    metadata:
      labels:
        app: test-statefulset
    spec:
      containers:
        - name: test-container
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test-daemonset
spec:
  selector:
    matchLabels:
      app: test-daemonset
  template:
    metadata:
      labels:
        app: test-daemonset
    spec:
      containers:
        - name: test-container
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fibonacci-job
  labels:
    app: fibonacci-job
spec:
  template:
    metadata:
      labels:
        app: fibonacci-job
    spec:
      containers:
      - name: fibonacci
        image: sandipandevzero/fibonacci:latest
        imagePullPolicy: Always
        env:
        - name: FIBONACCI_INTERVAL
          value: "1"
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 300m
            memory: 300Mi
      restartPolicy: Never
  backoffLimit: 3

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: fibonacci-cronjob
  labels:
    app: fibonacci-cronjob
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: fibonacci-cronjob
        spec:
          containers:
          - name: fibonacci
            image: sandipandevzero/fibonacci:latest
            imagePullPolicy: Always
            env:
            - name: FIBONACCI_INTERVAL
              value: "1"
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
              limits:
                cpu: 200m
                memory: 200Mi
          restartPolicy: OnFailure
      backoffLimit: 2
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3

---
apiVersion: v1
kind: Service
metadata:
  name: fibonacci-service
  labels:
    app: fibonacci-service
spec:
  selector:
    app: fibonacci-deploy
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: fibonacci-pod1
  labels:
    app: fibonacci-pod1
spec:
  containers:
  - name: fibonacci
    image: sandipandevzero/fibonacci:latest
    imagePullPolicy: Always
    env:
    - name: FIBONACCI_INTERVAL
      value: "1"
    resources:
      requests:
        cpu: 200m
        memory: 200Mi
      limits:
        cpu: 300m
        memory: 300Mi
  restartPolicy: Always
